version: '3.3'

services:
  app1:
    build: 
      context: service_author
      dockerfile: Dockerfile
    container_name: service_author
    networks:
      - arch-network    
    ports:
      - 8081:8081

  app2:
    build:
      context: service_presentation
      dockerfile: Dockerfile
    container_name: service_presentation
    networks:
      - arch-network
    ports:
      - 8082:8082

  app3:
    build:
      context: service_main
      dockerfile: Dockerfile
    container_name: service_main
    depends_on:
      - app1
      - app2
    networks:
      - arch-network
    ports:
      - 8083:8083


      
networks:
  arch-network:
    driver: "bridge"
    external: false
